const CITIES = [
  // North America
  { id: 'new-york', name: 'New York', country: 'United States', code: 'US', tz: 'America/New_York' },
  { id: 'los-angeles', name: 'Los Angeles', country: 'United States', code: 'US', tz: 'America/Los_Angeles' },
  { id: 'chicago', name: 'Chicago', country: 'United States', code: 'US', tz: 'America/Chicago' },
  { id: 'denver', name: 'Denver', country: 'United States', code: 'US', tz: 'America/Denver' },
  { id: 'phoenix', name: 'Phoenix', country: 'United States', code: 'US', tz: 'America/Phoenix' },
  { id: 'san-francisco', name: 'San Francisco', country: 'United States', code: 'US', tz: 'America/Los_Angeles' },
  { id: 'seattle', name: 'Seattle', country: 'United States', code: 'US', tz: 'America/Los_Angeles' },
  { id: 'miami', name: 'Miami', country: 'United States', code: 'US', tz: 'America/New_York' },
  { id: 'boston', name: 'Boston', country: 'United States', code: 'US', tz: 'America/New_York' },
  { id: 'washington', name: 'Washington DC', country: 'United States', code: 'US', tz: 'America/New_York' },
  { id: 'dallas', name: 'Dallas', country: 'United States', code: 'US', tz: 'America/Chicago' },
  { id: 'houston', name: 'Houston', country: 'United States', code: 'US', tz: 'America/Chicago' },
  { id: 'toronto', name: 'Toronto', country: 'Canada', code: 'CA', tz: 'America/Toronto' },
  { id: 'vancouver', name: 'Vancouver', country: 'Canada', code: 'CA', tz: 'America/Vancouver' },
  { id: 'montreal', name: 'Montreal', country: 'Canada', code: 'CA', tz: 'America/Toronto' },
  { id: 'mexico-city', name: 'Mexico City', country: 'Mexico', code: 'MX', tz: 'America/Mexico_City' },
  { id: 'honolulu', name: 'Honolulu', country: 'United States', code: 'US', tz: 'Pacific/Honolulu' },
  { id: 'anchorage', name: 'Anchorage', country: 'United States', code: 'US', tz: 'America/Anchorage' },

  // South America
  { id: 'sao-paulo', name: 'São Paulo', country: 'Brazil', code: 'BR', tz: 'America/Sao_Paulo' },
  { id: 'rio', name: 'Rio de Janeiro', country: 'Brazil', code: 'BR', tz: 'America/Sao_Paulo' },
  { id: 'brasilia', name: 'Brasília', country: 'Brazil', code: 'BR', tz: 'America/Sao_Paulo' },
  { id: 'buenos-aires', name: 'Buenos Aires', country: 'Argentina', code: 'AR', tz: 'America/Argentina/Buenos_Aires' },
  { id: 'santiago', name: 'Santiago', country: 'Chile', code: 'CL', tz: 'America/Santiago' },
  { id: 'lima', name: 'Lima', country: 'Peru', code: 'PE', tz: 'America/Lima' },
  { id: 'bogota', name: 'Bogotá', country: 'Colombia', code: 'CO', tz: 'America/Bogota' },
  { id: 'caracas', name: 'Caracas', country: 'Venezuela', code: 'VE', tz: 'America/Caracas' },

  // Europe
  { id: 'london', name: 'London', country: 'United Kingdom', code: 'GB', tz: 'Europe/London' },
  { id: 'paris', name: 'Paris', country: 'France', code: 'FR', tz: 'Europe/Paris' },
  { id: 'berlin', name: 'Berlin', country: 'Germany', code: 'DE', tz: 'Europe/Berlin' },
  { id: 'rome', name: 'Rome', country: 'Italy', code: 'IT', tz: 'Europe/Rome' },
  { id: 'madrid', name: 'Madrid', country: 'Spain', code: 'ES', tz: 'Europe/Madrid' },
  { id: 'amsterdam', name: 'Amsterdam', country: 'Netherlands', code: 'NL', tz: 'Europe/Amsterdam' },
  { id: 'brussels', name: 'Brussels', country: 'Belgium', code: 'BE', tz: 'Europe/Brussels' },
  { id: 'vienna', name: 'Vienna', country: 'Austria', code: 'AT', tz: 'Europe/Vienna' },
  { id: 'stockholm', name: 'Stockholm', country: 'Sweden', code: 'SE', tz: 'Europe/Stockholm' },
  { id: 'oslo', name: 'Oslo', country: 'Norway', code: 'NO', tz: 'Europe/Oslo' },
  { id: 'copenhagen', name: 'Copenhagen', country: 'Denmark', code: 'DK', tz: 'Europe/Copenhagen' },
  { id: 'dublin', name: 'Dublin', country: 'Ireland', code: 'IE', tz: 'Europe/Dublin' },
  { id: 'lisbon', name: 'Lisbon', country: 'Portugal', code: 'PT', tz: 'Europe/Lisbon' },
  { id: 'warsaw', name: 'Warsaw', country: 'Poland', code: 'PL', tz: 'Europe/Warsaw' },
  { id: 'prague', name: 'Prague', country: 'Czech Republic', code: 'CZ', tz: 'Europe/Prague' },
  { id: 'budapest', name: 'Budapest', country: 'Hungary', code: 'HU', tz: 'Europe/Budapest' },
  { id: 'athens', name: 'Athens', country: 'Greece', code: 'GR', tz: 'Europe/Athens' },
  { id: 'helsinki', name: 'Helsinki', country: 'Finland', code: 'FI', tz: 'Europe/Helsinki' },
  { id: 'reykjavik', name: 'Reykjavik', country: 'Iceland', code: 'IS', tz: 'Atlantic/Reykjavik' },
  { id: 'kyiv', name: 'Kyiv', country: 'Ukraine', code: 'UA', tz: 'Europe/Kyiv' },
  { id: 'bucharest', name: 'Bucharest', country: 'Romania', code: 'RO', tz: 'Europe/Bucharest' },
  { id: 'sofia', name: 'Sofia', country: 'Bulgaria', code: 'BG', tz: 'Europe/Sofia' },
  { id: 'belgrade', name: 'Belgrade', country: 'Serbia', code: 'RS', tz: 'Europe/Belgrade' },
  { id: 'zurich', name: 'Zurich', country: 'Switzerland', code: 'CH', tz: 'Europe/Zurich' },
  { id: 'moscow', name: 'Moscow', country: 'Russia', code: 'RU', tz: 'Europe/Moscow' },
  { id: 'istanbul', name: 'Istanbul', country: 'Turkey', code: 'TR', tz: 'Europe/Istanbul' },

  // Middle East
  { id: 'dubai', name: 'Dubai', country: 'United Arab Emirates', code: 'AE', tz: 'Asia/Dubai' },
  { id: 'abu-dhabi', name: 'Abu Dhabi', country: 'United Arab Emirates', code: 'AE', tz: 'Asia/Dubai' },
  { id: 'doha', name: 'Doha', country: 'Qatar', code: 'QA', tz: 'Asia/Qatar' },
  { id: 'riyadh', name: 'Riyadh', country: 'Saudi Arabia', code: 'SA', tz: 'Asia/Riyadh' },
  { id: 'jeddah', name: 'Jeddah', country: 'Saudi Arabia', code: 'SA', tz: 'Asia/Riyadh' },
  { id: 'kuwait', name: 'Kuwait City', country: 'Kuwait', code: 'KW', tz: 'Asia/Kuwait' },
  { id: 'manama', name: 'Manama', country: 'Bahrain', code: 'BH', tz: 'Asia/Bahrain' },
  { id: 'muscat', name: 'Muscat', country: 'Oman', code: 'OM', tz: 'Asia/Muscat' },
  { id: 'tehran', name: 'Tehran', country: 'Iran', code: 'IR', tz: 'Asia/Tehran' },
  { id: 'baghdad', name: 'Baghdad', country: 'Iraq', code: 'IQ', tz: 'Asia/Baghdad' },
  { id: 'beirut', name: 'Beirut', country: 'Lebanon', code: 'LB', tz: 'Asia/Beirut' },
  { id: 'tel-aviv', name: 'Tel Aviv', country: 'Israel', code: 'IL', tz: 'Asia/Jerusalem' },
  { id: 'jerusalem', name: 'Jerusalem', country: 'Israel', code: 'IL', tz: 'Asia/Jerusalem' },
  { id: 'baku', name: 'Baku', country: 'Azerbaijan', code: 'AZ', tz: 'Asia/Baku' },
  { id: 'tbilisi', name: 'Tbilisi', country: 'Georgia', code: 'GE', tz: 'Asia/Tbilisi' },

  // Asia
  { id: 'tokyo', name: 'Tokyo', country: 'Japan', code: 'JP', tz: 'Asia/Tokyo' },
  { id: 'osaka', name: 'Osaka', country: 'Japan', code: 'JP', tz: 'Asia/Tokyo' },
  { id: 'seoul', name: 'Seoul', country: 'South Korea', code: 'KR', tz: 'Asia/Seoul' },
  { id: 'beijing', name: 'Beijing', country: 'China', code: 'CN', tz: 'Asia/Shanghai' },
  { id: 'shanghai', name: 'Shanghai', country: 'China', code: 'CN', tz: 'Asia/Shanghai' },
  { id: 'hong-kong', name: 'Hong Kong', country: 'China', code: 'HK', tz: 'Asia/Hong_Kong' },
  { id: 'singapore', name: 'Singapore', country: 'Singapore', code: 'SG', tz: 'Asia/Singapore' },
  { id: 'bangkok', name: 'Bangkok', country: 'Thailand', code: 'TH', tz: 'Asia/Bangkok' },
  { id: 'hanoi', name: 'Hanoi', country: 'Vietnam', code: 'VN', tz: 'Asia/Ho_Chi_Minh' },
  { id: 'ho-chi-minh', name: 'Ho Chi Minh City', country: 'Vietnam', code: 'VN', tz: 'Asia/Ho_Chi_Minh' },
  { id: 'jakarta', name: 'Jakarta', country: 'Indonesia', code: 'ID', tz: 'Asia/Jakarta' },
  { id: 'kuala-lumpur', name: 'Kuala Lumpur', country: 'Malaysia', code: 'MY', tz: 'Asia/Kuala_Lumpur' },
  { id: 'manila', name: 'Manila', country: 'Philippines', code: 'PH', tz: 'Asia/Manila' },
  { id: 'taipei', name: 'Taipei', country: 'Taiwan', code: 'TW', tz: 'Asia/Taipei' },
  { id: 'dhaka', name: 'Dhaka', country: 'Bangladesh', code: 'BD', tz: 'Asia/Dhaka' },
  { id: 'yangon', name: 'Yangon', country: 'Myanmar', code: 'MM', tz: 'Asia/Yangon' },

  // South Asia
  { id: 'new-delhi', name: 'New Delhi', country: 'India', code: 'IN', tz: 'Asia/Kolkata' },
  { id: 'mumbai', name: 'Mumbai', country: 'India', code: 'IN', tz: 'Asia/Kolkata' },
  { id: 'bangalore', name: 'Bangalore', country: 'India', code: 'IN', tz: 'Asia/Kolkata' },
  { id: 'chennai', name: 'Chennai', country: 'India', code: 'IN', tz: 'Asia/Kolkata' },
  { id: 'kolkata', name: 'Kolkata', country: 'India', code: 'IN', tz: 'Asia/Kolkata' },
  { id: 'hyderabad', name: 'Hyderabad', country: 'India', code: 'IN', tz: 'Asia/Kolkata' },
  { id: 'karachi', name: 'Karachi', country: 'Pakistan', code: 'PK', tz: 'Asia/Karachi' },
  { id: 'islamabad', name: 'Islamabad', country: 'Pakistan', code: 'PK', tz: 'Asia/Karachi' },
  { id: 'lahore', name: 'Lahore', country: 'Pakistan', code: 'PK', tz: 'Asia/Karachi' },
  { id: 'kathmandu', name: 'Kathmandu', country: 'Nepal', code: 'NP', tz: 'Asia/Kathmandu' },
  { id: 'colombo', name: 'Colombo', country: 'Sri Lanka', code: 'LK', tz: 'Asia/Colombo' },
  { id: 'kabul', name: 'Kabul', country: 'Afghanistan', code: 'AF', tz: 'Asia/Kabul' },
  { id: 'tashkent', name: 'Tashkent', country: 'Uzbekistan', code: 'UZ', tz: 'Asia/Tashkent' },
  { id: 'almaty', name: 'Almaty', country: 'Kazakhstan', code: 'KZ', tz: 'Asia/Almaty' },

  // Africa
  { id: 'cairo', name: 'Cairo', country: 'Egypt', code: 'EG', tz: 'Africa/Cairo' },
  { id: 'lagos', name: 'Lagos', country: 'Nigeria', code: 'NG', tz: 'Africa/Lagos' },
  { id: 'abuja', name: 'Abuja', country: 'Nigeria', code: 'NG', tz: 'Africa/Lagos' },
  { id: 'nairobi', name: 'Nairobi', country: 'Kenya', code: 'KE', tz: 'Africa/Nairobi' },
  { id: 'johannesburg', name: 'Johannesburg', country: 'South Africa', code: 'ZA', tz: 'Africa/Johannesburg' },
  { id: 'cape-town', name: 'Cape Town', country: 'South Africa', code: 'ZA', tz: 'Africa/Johannesburg' },
  { id: 'casablanca', name: 'Casablanca', country: 'Morocco', code: 'MA', tz: 'Africa/Casablanca' },
  { id: 'algiers', name: 'Algiers', country: 'Algeria', code: 'DZ', tz: 'Africa/Algiers' },
  { id: 'tunis', name: 'Tunis', country: 'Tunisia', code: 'TN', tz: 'Africa/Tunis' },
  { id: 'addis-ababa', name: 'Addis Ababa', country: 'Ethiopia', code: 'ET', tz: 'Africa/Addis_Ababa' },
  { id: 'dakar', name: 'Dakar', country: 'Senegal', code: 'SN', tz: 'Africa/Dakar' },
  { id: 'accra', name: 'Accra', country: 'Ghana', code: 'GH', tz: 'Africa/Accra' },
  { id: 'luanda', name: 'Luanda', country: 'Angola', code: 'AO', tz: 'Africa/Lagos' },
  { id: 'harare', name: 'Harare', country: 'Zimbabwe', code: 'ZW', tz: 'Africa/Harare' },
  { id: 'kinshasa', name: 'Kinshasa', country: 'DR Congo', code: 'CD', tz: 'Africa/Kinshasa' },
  { id: 'khartoum', name: 'Khartoum', country: 'Sudan', code: 'SD', tz: 'Africa/Khartoum' },

  // Oceania
  { id: 'sydney', name: 'Sydney', country: 'Australia', code: 'AU', tz: 'Australia/Sydney' },
  { id: 'melbourne', name: 'Melbourne', country: 'Australia', code: 'AU', tz: 'Australia/Melbourne' },
  { id: 'brisbane', name: 'Brisbane', country: 'Australia', code: 'AU', tz: 'Australia/Brisbane' },
  { id: 'perth', name: 'Perth', country: 'Australia', code: 'AU', tz: 'Australia/Perth' },
  { id: 'adelaide', name: 'Adelaide', country: 'Australia', code: 'AU', tz: 'Australia/Adelaide' },
  { id: 'auckland', name: 'Auckland', country: 'New Zealand', code: 'NZ', tz: 'Pacific/Auckland' },
  { id: 'wellington', name: 'Wellington', country: 'New Zealand', code: 'NZ', tz: 'Pacific/Auckland' },
  { id: 'suva', name: 'Suva', country: 'Fiji', code: 'FJ', tz: 'Pacific/Fiji' },
  { id: 'port-moresby', name: 'Port Moresby', country: 'Papua New Guinea', code: 'PG', tz: 'Pacific/Port_Moresby' },
  { id: 'noumea', name: 'Nouméa', country: 'New Caledonia', code: 'NC', tz: 'Pacific/Noumea' },

  // Pacific
  { id: 'apia', name: 'Apia', country: 'Samoa', code: 'WS', tz: 'Pacific/Apia' },
  { id: 'pago-pago', name: 'Pago Pago', country: 'American Samoa', code: 'AS', tz: 'Pacific/Pago_Pago' },

  // Additional European
  { id: 'milan', name: 'Milan', country: 'Italy', code: 'IT', tz: 'Europe/Rome' },
  { id: 'barcelona', name: 'Barcelona', country: 'Spain', code: 'ES', tz: 'Europe/Madrid' },
  { id: 'munich', name: 'Munich', country: 'Germany', code: 'DE', tz: 'Europe/Berlin' },
  { id: 'hamburg', name: 'Hamburg', country: 'Germany', code: 'DE', tz: 'Europe/Berlin' },
  { id: 'minneapolis', name: 'Minneapolis', country: 'United States', code: 'US', tz: 'America/Chicago' },
  { id: 'atlanta', name: 'Atlanta', country: 'United States', code: 'US', tz: 'America/New_York' },
  { id: 'calgary', name: 'Calgary', country: 'Canada', code: 'CA', tz: 'America/Edmonton' },
];

const CITY_MAP = {};
CITIES.forEach(c => { CITY_MAP[c.id] = c; });
